### ISSUE TITLE
Missing perl script  freq_extract.plj

### ISSUE THREAD

**Issue by weiju** [MtbEvolution/resR_Project#2]
Hi,
we are currently trying to replicate results using the 0_Unfixed_SNPs_Calling.sh pipeline. I noticed that there is a call to a freq_extract.pl script and I can't seem to find this in the github repository. Is it perhaps missing ?

Thanks

**Comment by MtbEvolution** [comment]
Hi,
Just uploaded.
Best,
Qingyun

On Dec 12, 2023, at 14:50, Wei-ju Wu ***@***.******@***.***>> wrote:



Hi,
we are currently trying to replicate results using the 0_Unfixed_SNPs_Calling.sh pipeline. I noticed that there is a call to a freq_extract.pl script and I can't seem to find this in the github repository. Is it perhaps missing ?

Thanks

**Comment by weiju** [comment]
Thank you so much !
