### ISSUE TITLE
Unfixed pipeline: format_trans.pl returns empty file on .ppe file

### ISSUE THREAD

**Issue by weiju** [MtbEvolution/resR_Project#3]
Hi, we are having trouble getting results out of the Unfixed pipeline. One problem seems to be that the Perl script format_trans.pl returns an empty file.
As I understand the PPE file is created from PE_IS_filt.pl from a .varscan file and this actually generates a file.

I am not particularly fluent with Perl, but as I understand it, it rearranges the file structure. 

To me, this section 
if($_=~m/^Chrom/){
}else{
	@a=split "\t",$_;

will only process the lines that don't begin with "Chrom", however, our PPE file looks like this:

============= PPE FILE
Chrom   Position        Ref     Var     Cons:Cov:Reads1:Reads2:Freq:P-value     StrandFilter:R1+:R1-:R2+:R2-:pval       SamplesRef      SamplesHet      SamplesHom      SamplesNC       Cons:Cov:Reads1:Reads2:Freq:P-value
Chromosome      293     T       C       Y:115:113:2:1.74%:9.8E-1        Pass:1.0:56:57:2:0:2.5217E-1    0       1       0       0       Y:115:113:2:1.74%:9.8E-1
Chromosome      294     C       A       M:114:112:2:1.75%:9.8E-1        Pass:1.0:57:55:2:0:2.6564E-1    0       1       0       0       M:114:112:2:1.75%:9.8E-1
....
=========== PPE FILE END

So every line starts with Chrom. My assumption is that the PPE/VARSCAN file is not  in the format that format_trans.pl expects ? 

Any thoughts about this are appreciated, I think all the subsequent pipeline steps are affected by this 

Thanks !

**Comment by weiju** [comment]
I am able to proceed here by 

changing

if($=~m/^Chrom/){

to 

if($=~m/^Chrom\t/){

**Comment by MtbEvolution** [comment]
Excellent!

Thanks for the update! Let me know if there is any other question.

On Dec 15, 2023, at 13:31, Wei-ju Wu ***@***.******@***.***>> wrote:



I am able to proceed here by

changing

if($=~m/^Chrom/){

to

if($=~m/^Chrom\t/){
